### ISSUE TITLE
Error when launching comfyUI, error with DT_PromptGen node / downloading gpt2 model 

### ISSUE THREAD

**Issue by kerbi** [diontimmer/ComfyUI-Vextra-Nodes#4]
Hi ! Got an error when lauching ComfyUI that prevented your nodes from being loaded.

Error is in DT_PromptGen.py, when it loads, it does the error I posted below.

Line 14 it tried to load a model it didn't successfully downloaded for some reason.

Don't know how to properly fix it, for now I bypassed the error by copying line 8 and putting it above the three lines from 12 to 14 :

Now :
```
if os.path.exists(f'{comfy_path}custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2'):
	tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')
	tokenizer.add_special_tokens({'pad_token': '[PAD]'})
	model = GPT2LMHeadModel.from_pretrained(f'{comfy_path}custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2')
```
Previous :
```
tokenizer = GPT2Tokenizer.from_pretrained('distilgpt2')
tokenizer.add_special_tokens({'pad_token': '[PAD]'})
model = GPT2LMHeadModel.from_pretrained(f'{comfy_path}custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2')
```

The error :

```
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Downloading model...
fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering

Traceback (most recent call last):
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\transformers\configuration_utils.py", line 620, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'F:\Stable Diffusion\comfyui\custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Stable Diffusion\comfyui\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable Diffusion\comfyui\custom_nodes\ComfyUI-Vextra-Nodes\__init__.py", line 9, in <module>
    node_import = importlib.import_module('custom_nodes.ComfyUI-Vextra-Nodes.nodes.' + node)
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable Diffusion\comfyui\custom_nodes\ComfyUI-Vextra-Nodes\__init__.py", line 9, in <module>
    node_import = importlib.import_module('custom_nodes.ComfyUI-Vextra-Nodes.nodes.' + node)
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable Diffusion\comfyui\custom_nodes\ComfyUI-Vextra-Nodes\nodes\DT_PromptGen.py", line 14, in <module>
    model = GPT2LMHeadModel.from_pretrained(f'{comfy_path}custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2')
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\transformers\modeling_utils.py", line 2079, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\transformers\configuration_utils.py", line 538, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\transformers\configuration_utils.py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Antoine\anaconda3\envs\comfyui\lib\site-packages\transformers\configuration_utils.py", line 641, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'F:\Stable Diffusion\comfyui\custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'F:\Stable Diffusion\comfyui\custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2' is the correct path to a directory containing a config.json file

Cannot import F:\Stable Diffusion\comfyui\custom_nodes\ComfyUI-Vextra-Nodes module for custom nodes: Can't load the configuration of 'F:\Stable Diffusion\comfyui\custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'F:\Stable Diffusion\comfyui\custom_nodes/ComfyUI-Vextra-Nodes/binary/distilgpt2-stable-diffusion-v2' is the correct path to a directory containing a config.json file
### Loading: ComfyUI-Workflow-Component (V0.41.4) !! WARN: This is an experimental extension. Extremely unstable. !!
Registered sys.path: ['F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\comfyui_controlnet_aux\\src', 'F:\\Stable Diffusion\\comfyui\\comfy', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\lib\\site-packages\\git\\ext\\gitdb', 'F:\\Stable Diffusion\\comfyui', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\python310.zip', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\DLLs', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\lib', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\lib\\site-packages', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\lib\\site-packages\\win32', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Antoine\\anaconda3\\envs\\comfyui\\lib\\site-packages\\Pythonwin', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\ComfyUI-Impact-Pack\\subpack', '../..', 'F:\\Stable Diffusion\\comfyui\\custom_nodes\\ComfyUI-Workflow-Component']
```

I'm using a conda env, and i'm running windows 10.

Thanks for the nodes btw !

**Comment by PolarisFx** [comment]
Ran into the same problem, just in linux. Just download the models manually. You can find them here:

https://huggingface.co/FredZhang7/distilgpt2-stable-diffusion-v2/tree/main

Not sure which one it's looking for so grab mode.safetensors and pytorch_model.bin, and then put them in:

ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes\binary\distilgpt2-stable-diffusion-v2

Should start fine after that.
